### ISSUE TITLE
Day 7 Take Home Challenge: Recreate parallax practice mockup

### ISSUE THREAD

**Issue by im-amy-lew** [im-amy-lew/parallax-practice#1]
**To-do:**
- [x] Create new branch named `take-home`
- [x] Add two fonts from Google Fonts
- [x] Add `img` folder with background images
- [x] Add navbar with links to all page sections
- [x] Add jumbotron
- [x] Add `main` content
- [x] Add parallax scrolling effect to all sections
- [x] Add `footer` with social media links
- [x] Change text to reflect mockup
- [x] Add buttons between sections
- [x] Fix text box styling to match mockup
- [x] Adjust styling for smaller screens
- [x] Add, commit, and push changes to `take-home`
- [x] Open a PR
- [x] Request review from collaborator
